name: flutter_k_chart
description: flutter_k_chart, Writted with pure dart, supported both iOS and Android.
version: 0.2.0
homepage: https://gitlab.me/flutter/flutter_k_chart
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
flutter_intl:
  enabled: true
